codecov:
  token: f12c1d96-5043-455c-b481-7eba8faeec91
  bot: "codecov-io"
  ci:
    - "travis.org"
  require_ci_to_pass: yes
coverage:
  range: 0..100
  round: nearest
  percision: 2
  ignore:
    - test_*.py
    - apioxy/_version.py
comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  branches: master
